services:
  postgres:
    image: postgres:15
    restart: always
    container_name: speedat_auth_1
    environment:
      POSTGRES_USER: speedat_auth_1
      POSTGRES_PASSWORD: speedat_auth_1
      POSTGRES_DB: speedat_auth_1
      MAIL_HOST: smtp.zoho.com
      MAIL_PORT: 456
      MAIL_SECURE: true
      MAIL_USER: verify@speedat.site
      MAIL_PASSWORD: js9xUc!g
    ports:
      - "5433:5432"
    volumes:
      - speedat_auth_1_data:/var/lib/postgresql/data/

volumes:
  speedat_auth_1_data:
