version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: always
    volumes:
      - ./mysql-data:/var/lib/mysql # 데이터베이스 데이터를 호스트에 저장
    ports:
      - "3306:3306" # 호스트에서 접근 가능하도록 포트 포워딩 설정
    environment:
      MYSQL_ROOT_PASSWORD: Dkswlgl12#*  # 루트 계정 비밀번호 (안전한 비밀번호로 변경)
      MYSQL_DATABASE: speedat_auth # 데이터베이스 이름
      MYSQL_USER: root # 데이터베이스 사용자 이름
      MYSQL_PASSWORD: Dkswlgl12#* # 데이터베이스 사용자 비밀번호