version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: always
    volumes:
      - ./mysql-data:/var/lib/mysql 
    ports:
      - "3306:3306" 
    environment:
      MYSQL_ROOT_PASSWORD: Dkswlgl12#*  # 루트 계정 비밀번호 설정
      MYSQL_DATABASE: speedat_auth # 데이터베이스 이름 

  backend: # 백엔드 서비스 추가
    build: .
    ports:
      - "3000:3000" # 호스트 포트:컨테이너 포트
    depends_on:
      - mysql # MySQL 컨테이너가 먼저 실행되도록 설정
    environment:
      DB_HOST: mysql # MySQL 컨테이너 이름
      DB_PORT: 3306
      DB_USERNAME: root # MySQL 루트 계정 사용
      DB_PASSWORD: Dkswlgl12#* # MySQL 루트 계정 비밀번호
      DB_NAME: speedat_auth